### ISSUE TITLE
The project isn't same as the screenshots.

### ISSUE THREAD

**Issue by shakib-h** [Akashdu/FlutterQuizzApp#1]
Hi there, 
I see the app is not same as you described, is this project under development?

**Comment by Akashdu** [comment]
Github Par update Nahin Kiye Hain Abhi

**Comment by shakib-h** [comment]
Oh okay, that's a cool project. Do you have any plan to upload it...?

**Comment by Akashdu** [comment]
Yes i do it for 2-3 days
